### ISSUE TITLE
Recent List is Shown Over Debug Toolbar

### ISSUE THREAD

**Issue by MiyaNoctem** [davialexandre/br.com.davialexandre.civicrm.debugtoolbar#1]
## Overview
When there si  long list of items on recently used list, some links of the toolbar are unable to be used, as the list is shown over the toolbar.

![image](https://user-images.githubusercontent.com/21999940/39765008-79293b9e-52a6-11e8-9b99-c83f5b0da88b.png)

**Comment by davialexandre** [comment]
fixed by https://github.com/davialexandre/br.com.davialexandre.civicrm.debugtoolbar/pull/2
